feat: Refactor asset upload logic to handle multiple binaries

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,16 +18,18 @@ runs:
           echo "Failed to create github release"
           exit 1
         fi
-        if [ -z "$BIN_NAME" ]; then
-          echo "No binary to upload"
+        if [ -z "$BIN_NAMES" ]; then
+          echo "No binaries to upload"
         else
-          RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data-binary @"target/$BIN_NAME" "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$BIN_NAME")
-          ASSET_ID="$(echo "$RESPONSE" | jq -r '.id')"
-          if [[ "$ASSET_ID" != null ]]; then
-            echo "Asset uploaded successfully!: ASSET_ID=$ASSET_ID"
-          else
-            echo "RESPONSE=$RESPONSE"
-            echo "Failed to upload asset. RESPONSE: $RESPONSE"
-            exit 1
-          fi
+          for BIN_NAME in $BIN_NAMES; do
+            RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data-binary @"target/$BIN_NAME" "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$BIN_NAME")
+            ASSET_ID="$(echo "$RESPONSE" | jq -r '.id')"
+            if [[ "$ASSET_ID" != null ]]; then
+              echo "Asset uploaded successfully!: ASSET_ID=$ASSET_ID"
+            else
+              echo "RESPONSE=$RESPONSE"
+              echo "Failed to upload asset. RESPONSE: $RESPONSE"
+              exit 1
+            fi
+          done
         fi
